# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NGIN2BkCuUt-iwioBYwsEQh62HnXYTki

B.ANUPAMA
20221BCA0296

4/09/2023(MON)
"""

import numpy as np
a=np.array([1,3,0],float)
print(a>2)

import numpy as np
a=np.array([1,3,0],float)
print(a)

print(a[0])

print(a[-1])

import numpy as np
a=np.array([2,3,4])
print(type(a))

b=np.array((2,3,4))
print(type(b))

a=np.array([[1,3,0],[2,4,6]])
print(a[0][0])

a=np.array([[1,3,0],[2,4,6],[5,6,7]])
print(a[2][1])

arr=np.zeros((3,3),int)
print(arr)

arr=np.ones((3,3),int)
print(arr)

arr=np.empty((3,4),int)
print(arr)

arr=np.arange(10,30,5)
print(arr)

arr=np.arange(0,2,0.3)
print(arr)

arr=np.arange(0,10,2)
print(arr)

arr=np.arange(1,11,2)
print(arr)

arr=np.linspace(0,2,9)
print(arr)

help(np.linspace)

import numpy as np
x=np.random.randint(10,30,6)
print(x)

import numpy as np
x=np.random.randint(-10,30,12)
print(x)

"""11/09/2023(MON)"""

!python --version

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([7,8,12,15,2,4,6]))

x=3
print(x,type(x))

print(x + 4)
print(x - 2)
print(x * 3)
print(x ** 2)

x += 1
print(x)
x *= 2
print(x)

y = 5.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

t, f = True, False
print(type(t))

